# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :beta do
    app_store_connect_api_key(
      key_id: "3JLY57233A",
      issuer_id: "2e36e933-ab8c-410c-ab80-c625f6f2149f",
      key_filepath: "/Users/jackson/Desktop/gif_project/fastlane/key.p8"
    )
    sync_code_signing(type: "appstore")
    build_app(scheme: "gif_project")
    upload_to_testflight
  end
end
